# Generated by Django 4.1 on 2022-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='paragraph',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
