# Generated by Django 4.1 on 2022-08-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_event_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
