# Generated by Django 4.1 on 2022-08-26 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_paragraph_event_paragraph_1_event_paragraph_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Incorrect phone number (xxx xxx xxxx)', regex='^(\\d{3}[- .]?){2}\\d{4}$')])),
                ('people', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date', '-is_processed'),
            },
        ),
    ]
