# Generated by Django 4.1 on 2022-08-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userreservationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReservationForm',
            new_name='UserReservation',
        ),
    ]
